name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install puppeteer
      run: yarn add puppeteer
    - name: Run a multi-line script
      run: |
        node example.js

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@2.1.0
      with:
        path: example.png
